FORMAT: 1A
HOST: http://creditcheck.example.org/

# Credit Check API

Credit Check API for BigCo, Inc

## Home [/]

### Show Home Page [GET]

+ Response 200 (text/plain)

        HOME

## Credit Check History List [/history]

### Show Credit Check History List [GET]

+ Response 200 (application/forms+json)

    + Body

            {
              "home" : [
                {
                  "title":"Show Credit Check Recordst",
                  "forms":[
                    {"name":"list", "href":"/list"},
                    {"name":"create", "href":"/list", "method":"post",
                      "properties":[
                        {"name":"ratingId","value":"1q12w3e4r5t"}
                      ]
                    }
                  ],
                  "items":[
                    {"ratingId" : "1q2w3e4r5t", "href" : "/1q2w3e4r5t", "companyName":"Acme Corp", "ratingValue": "1", "dateRequested": "2020-09-01"}
                  ]
                }
              ]
            }


## Credit Check Form [/history/add]

### Show Add Credit Check Form [GET]
+ Response 200 (text/html)

        CREATE-FORM
        
### Create Credit Check Record [POST]

+ Request (application/x-www-form-urlencoded)

            ratingId=1q2w3e4r5t

+ Response 201 (application/forms+json)

    + Header 
        
            Location: history/1q2w3e4r5t

    + Body

            {
              "home" : [
                {
                  "title":"RATINGID:1q2w3e4r5t Created",
                  "forms":[
                    {"name":"list", "href":"/list"}
                  ],
                  "items":[
                     {"ratingId" : "1q2w3e4r5t", "href" : "/1q2w3e4r5t", "companyName":"Acme Corp", "ratingValue": "1", "dateRequested": "2020-09-01"}
                  ]
                }
              ]
            }

# Credit Check Record [/history/1q2w3e4r5t]

### Show Credit Check Record [GET]

+ Response 200 (text/plain)

        CREDIT-CHECK-ID:1q2w3e4r5t

